### ISSUE TITLE
Add convenience properties to `spy`

### ISSUE THREAD

**Issue by tommy-mitchell** [VanCoding/testtriple#4]
I know `testtriple` is focused on mocking and not asserting, but I think a couple of properties on `spy` could be convenient:

```ts
const spy = tt.spy(returns(1));
spy();

console.log(spy.called); // equivalent to `getFunctionCalls(spy).length > 0`
//=> true

console.log(spy.callCount); // equivalent to `getFunctionCalls(spy).length`
//=> 1
```

<details>
<summary>Possible implementation</summary>

```ts
type Spy<T, U = Extract<T, (...args: any) => any>> = {
  called: boolean;
  callCount: number;
} & (
  [U] extends [never]
    ? (...args: any) => void
    : U
);

export function spy<T>(
  ...functions: Extract<T, (...args: any) => any>[]
): Spy<T> {
  const functionCalls: FunctionCall[] = [];
  let functionMock = function (this: any, ...args: any): any {
    // ...
  };
  functionMock = Object.defineProperties(functionMock, {
    called: {
      get: () => getFunctionCalls(functionMock).length > 0,
      enumerable: true, // Not sure if these should be enumerable or not
    },
    callCount: {
      get: () => getFunctionCalls(functionMock).length,
      enumerable: true,
    },
  });
  calls.set(functionMock, functionCalls);
  return functionMock as any;
}
```

</details>

**Comment by tommy-mitchell** [comment]
Maybe an `explain` function (like [`td.explain`](https://github.com/testdouble/testdouble.js/blob/main/docs/9-debugging.md#tdexplainsometestdouble)) would work better:

```ts
type Explanation = {
	calls: Call[];
	callCount: number;
	called: boolean;
	// etc.
};

function explain(fn): Explanation { /* ... */ }
```

**Comment by VanCoding** [comment]
Yes, the explain function looks appealing to me. The reason why i wouldn't want additional properties directly on the spy is, that it would require to return an extended type from the original function. But in most cases, the spy is assigned to a property or variable of the original type, which erases the additional properties, and casting would be necessary.

I think I'll look into adding something like explain when i find some time for it. Thanks for the suggestion :)

**Comment by tommy-mitchell** [comment]
Are you open to PRs?

**Comment by VanCoding** [comment]
@tommy-mitchell Yes, sure. I'm not sure about the name "explain" yet, though. I'd prefer something that aligns a bit better with callsOf, allCallsOf and callOrderOf. Maybe something like "callDetailsOf" or "callSummaryOf"?

And we'd also need some tests for it.
